### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by pjdelport** [pipermerriam/populus#94]
This is to track what's needed to make Populus run on Python 3.

At least the following should be needed:

- [ ] Finish extracting ethereum-contract and ethereum-tester-client (#78)
- [ ] Conditional imports, such as `Queue` / `queue`
- [ ] String typing (`str` / `bytes`)

Python 3 support in upstream dependencies:

- [ ] pyethereum (<https://github.com/ethereum/pyethereum/issues/132>), or ethereum-abi-utils (<https://github.com/pipermerriam/ethereum-abi-utils/issues/1>)
- [ ] ethereum-contract (<https://github.com/pipermerriam/ethereum-contract/issues/2>)
- [ ] ethereum-tester-client (<https://github.com/pipermerriam/ethereum-tester-client/issues/2>)

#### Cute Animal Picture

![python](http://i.imgur.com/4rQ10nK.jpg)

**Comment by pjdelport** [comment]
I'm assuming the goal would be to remain Python 2.7 compatible, while that is supported.

Would introducing a dependency on `six` be out of the question?

**Comment by pipermerriam** [comment]
`six` is a welcome dependency.

I'd actually like to remove the `pyethereum` dependency in favor of using [`ethereum-abi-utils`](https://github.com/pipermerriam/ethereum-abi-utils)

**Comment by pipermerriam** [comment]
This is incoming in #105

**Comment by miohtama** [comment]
I am planning to merge my branch when you get 1.0.0 stabilitized, unless you have done Py3 cleanups yourself.

**Comment by pipermerriam** [comment]
Current master branch is happy in python 3

**Comment by pipermerriam** [comment]
Closing as this is currently in a beta release.
